export const LOAD_OPTIONS = "LOAD_OPTIONS";
export const CHANGE_PERSON = "CHANGE_PERSON";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const ADD_PROJECT = "ADD_PROJECT";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const LOAD_PROJECTS_SUCCESS = "LOAD_PROJECTS_SUCCESS";
export const LOGOUT = "LOGOUT";
